spring.application.name=crypto

crypto.symbols = XRPUSDT,BTCUSDT,ETHUSDT

spring.datasource.url=jdbc:postgresql://localhost:5432/cryptodb
spring.datasource.username=crypto
spring.datasource.password=crypto123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
